service: AIFitnessPlanner
# app and org for use with dashboard.serverless.com
app: serverless-app
org: sagaraj

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: 20201221
  timeout: 29

plugins:
  - serverless-plugin-include-dependencies

functions:
  DietPlanner:
    handler: handler.plan
    events:
    - http:
         path: diet
         method: post
         cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id
            allowCredentials: false

  WorkoutPlanner:
      handler: handler.workoutPlanner
      events:
      - http:
          path: workout
          method: post
          cors:
              origin: '*'
              headers:
                - Content-Type
                - X-Amz-Date
                - Authorization
                - X-Api-Key
                - X-Amz-Security-Token
                - X-Amz-User-Agent
                - X-Amzn-Trace-Id
              allowCredentials: false

